Algoritmo "conversor"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/4/2021
Var
// Seção de Declarações das variáveis 
   angulo, S: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Informe um angulo: ")
   Leia (angulo)
   S <- Sen(GraupRad(angulo))
   Escreva("O Seno de ", angulo, " e igual a ", s)

Fimalgoritmo